// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92YLpQEl7Bsv2iLw1ThI_pzMn3CgE-ig',
    appId: '1:1720527246:web:cc8598a08e15f6e32a5cdf',
    messagingSenderId: '1720527246',
    projectId: 'flutter-study-app-27973',
    authDomain: 'flutter-study-app-27973.firebaseapp.com',
    storageBucket: 'flutter-study-app-27973.firebasestorage.app',
    measurementId: 'G-EYQGXS8ER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtVXHFaYLMFP7kxfovvXcadLFLhAbWpek',
    appId: '1:1720527246:android:02c6ddd21f4a7c192a5cdf',
    messagingSenderId: '1720527246',
    projectId: 'flutter-study-app-27973',
    storageBucket: 'flutter-study-app-27973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9_Fq-pxmemphfzl0fK6x4OCwJNVXiyQ',
    appId: '1:1720527246:ios:157160fdf49c771a2a5cdf',
    messagingSenderId: '1720527246',
    projectId: 'flutter-study-app-27973',
    storageBucket: 'flutter-study-app-27973.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9_Fq-pxmemphfzl0fK6x4OCwJNVXiyQ',
    appId: '1:1720527246:ios:157160fdf49c771a2a5cdf',
    messagingSenderId: '1720527246',
    projectId: 'flutter-study-app-27973',
    storageBucket: 'flutter-study-app-27973.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD92YLpQEl7Bsv2iLw1ThI_pzMn3CgE-ig',
    appId: '1:1720527246:web:fca7ab65f67b8e902a5cdf',
    messagingSenderId: '1720527246',
    projectId: 'flutter-study-app-27973',
    authDomain: 'flutter-study-app-27973.firebaseapp.com',
    storageBucket: 'flutter-study-app-27973.firebasestorage.app',
    measurementId: 'G-JE9NBQMENJ',
  );
}
